### ISSUE TITLE
Training fails when dataset contains images without objects (loss_masks empty → backward hang / NCCL timeout)

### ISSUE THREAD

**Issue by eeNickTang** [Gorilla-Lab-SCUT/PaDT#21]
Hi, thanks for the great work — really impressive project!

I’m trying to train PaDT on my own dataset, which includes some images without any annotated objects.
Although the preprocessing code seems to contain logic for handling empty-object cases, the released training code appears not to support them.

When running sft_train.py, the trainer crashes here because loss_masks is an empty list:
```python
loss_masks = torch.cat(loss_masks, dim=0)
loss_masks = torch.nn.functional.pad(loss_masks, (self.model_embed_token_size, 0), 'constant', False)
gt_bboxes = torch.Tensor(gt_bboxes).to(self.accelerator.device).to(torch.bfloat16)
```

The error occurs because `loss_masks == []`.

---

# ✔️ My attempted fix

I modified compute_loss so that it can handle samples without objects (i.e., has_obj = False).
The modified implementation is shown below:
```python
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        rank = int(os.environ.get("RANK", None))
        
        if return_outputs:
            raise ValueError("The PaDTTrainer does not support returning outputs")

        prompt_text = [self.processing_class.apply_chat_template(i['prompt'], tokenize=False, add_generation_prompt=True) for i in inputs]
        
        images = []
        completions = []
        solutions = []
        for idx, x in enumerate(inputs):
            # input_images
            assert len(x['image_path']) == 1, "current support only an image per sample"

            for img in x['image_path']:
                image = PIL.Image.open(img)
                try:
                    w, h = image.size
                    if w < 28 or h < 28:
                        if w < h:
                            new_w = 28
                            new_h = int(h * (28 / w))
                        else:
                            new_h = 28
                            new_w = int(w * (28 / h))
                    image = image.resize((new_w, new_h), PIL.Image.Resampling.LANCZOS)
                except:
                    pass
                images.append(image)
            
            # completion
            im_w, im_h = image.size
            patch_w, patch_h = round(im_w / 28), round(im_h / 28)

            solution = x['solution']
            completion = solution['text']
            pattern = r'(<\|Obj_(\d+)\|>)'
            obj_in_completion = re.findall(pattern, completion)
            obj_strs = [i[0] for i in obj_in_completion]
            objs = [solution['objects'][int(i[1])] for i in obj_in_completion]
            pattern_without_matching = r'<\|Obj_\d+\|>'
            completion_parts = re.split(pattern_without_matching, completion)
            
            completion_with_vrt = completion_parts[0]
            new_objs = []
            for obj_str, completion_part, obj in zip(obj_strs, completion_parts[1:], objs):
                obj_ = obj.copy()
                selected_patches = np.array(obj_['patches'])
                if self.args.random_select_patch_num < 0:
                    pick_patch = selected_patches.copy()
                elif self.args.random_select_patch is False:
                    selected_patches_x, selected_patches_y = selected_patches % patch_w, selected_patches // patch_w
                    
                    left_patches_m = selected_patches_x == selected_patches_x.min()
                    right_patches_m = selected_patches_x == selected_patches_x.max()
                    top_patches_m = selected_patches_y == selected_patches_y.min()
                    bottom_patches_m = selected_patches_y == selected_patches_y.max()
                    centre_patches_m = (left_patches_m + right_patches_m + top_patches_m + bottom_patches_m) == 0                        
                    
                    left_patches, right_patches, top_patches, bottom_patches, centre_patches = \
                        selected_patches[left_patches_m], \
                        selected_patches[right_patches_m], \
                        selected_patches[top_patches_m], \
                        selected_patches[bottom_patches_m], \
                        selected_patches[centre_patches_m]
                    if centre_patches_m.sum() == 0:
                        centre_patches = selected_patches
                        
                    pick_patch = np.array([np.random.choice(centre_patches), np.random.choice(left_patches), np.random.choice(top_patches), np.random.choice(right_patches), np.random.choice(bottom_patches)])
                else:
                    if selected_patches.shape[0] < self.args.random_select_patch_num:
                        pick_patch = np.random.choice(selected_patches, self.args.random_select_patch_num, replace=True)
                    else:
                        pick_patch = np.random.choice(selected_patches, self.args.random_select_patch_num, replace=False)
            
                obj_['picked'] = pick_patch
                new_objs.append(obj_)
                completion_with_vrt += self.processing_class.pid2vrt(pick_patch) + completion_part

            solutions.append({
                'text': solution['text'],
                'objects': new_objs
            })
            completions.append(completion_with_vrt + self.processing_class.tokenizer.eos_token)

        # tokenizing
        prompt_inputs = self.processing_class(
            text=prompt_text,
            images=images,
            return_tensors='pt',
            padding=True,
            padding_side='left',
            add_special_tokens=False
        )
        prompt_inputs = super()._prepare_inputs(prompt_inputs)
        prompt_ids, prompt_mask = prompt_inputs["input_ids"], prompt_inputs["attention_mask"]
        batch_size = prompt_ids.size(0)
        prompt_length = prompt_ids.size(1)
        multimodal_inputs = {
            'image_grid_thw': prompt_inputs['image_grid_thw'],
            'pixel_values': prompt_inputs['pixel_values']
        }
        
        completion_inputs = self.processing_class(
            text=completions,
            return_tensors='pt',
            padding=True,
            padding_side='right',
            add_special_tokens=False
        )
        completion_inputs = super()._prepare_inputs(completion_inputs)
        completion_ids, completion_mask = completion_inputs["input_ids"], completion_inputs["attention_mask"]

        # prepare for Robust Per-token Cross-Entropy Loss.
        loss_masks = []
        gt_bboxes = []
        vision_patch_nums = torch.nn.functional.pad((multimodal_inputs['image_grid_thw'].cumprod(-1)[:, -1] // (self.model.config.vision_config.spatial_merge_size ** 2)).cumsum(-1), (1, 0), 'constant', 0)
        all_vision_patch_nums = vision_patch_nums[-1]
        for sol, vpn in zip(solutions, vision_patch_nums[:-1]):
            for obj in sol['objects']:
                this_object_loss_mask = torch.zeros((obj['picked'].shape[0], all_vision_patch_nums), device=self.accelerator.device, dtype=torch.bool)
                this_object_loss_mask[:, vpn.item() + np.array(obj['patches'])] = True
                this_object_loss_mask[np.arange(obj['picked'].shape[0]), vpn.item() + obj['picked']] = False
                loss_masks.append(this_object_loss_mask)
                # obj['bbox']: x1, y1, x2, y2. Value in [0, 1].
                gt_bboxes.append(obj['bbox'])
                
        
        if len(loss_masks) and len(gt_bboxes):
            has_obj = True
            loss_masks = torch.cat(loss_masks, dim=0)
            loss_masks = torch.nn.functional.pad(loss_masks, (self.model_embed_token_size, 0), 'constant', False)
            gt_bboxes = torch.Tensor(gt_bboxes).to(self.accelerator.device).to(torch.bfloat16)
            if len(gt_bboxes.shape) == 1:
                gt_bboxes = gt_bboxes.unsqueeze(dim=-1).repeat_interleave(4, dim=-1)
        else:
            has_obj = False
            

        # Concatenate for full sequence
        input_ids = torch.cat([prompt_ids, completion_ids], dim=1)
        attention_mask = torch.cat([prompt_mask, completion_mask], dim=1)

        input_ids = self.processing_class.assign_to_global_vrt_id(input_ids, multimodal_inputs['image_grid_thw'])

        # Get the current policy's log probabilities
        model_output = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True, **multimodal_inputs)

        logits = model_output.logits[:, prompt_length-1:-1, :]  # (B, L, V)
        input_ids = input_ids[:, prompt_length:]  # (B, L-1), exclude the first input ID since we don't have logits for it
        if self.args.use_sft_vp_mask and has_obj:
            visual_patch_mask = input_ids >= self.model_embed_token_size
            logits[visual_patch_mask] = logits[visual_patch_mask].masked_fill(loss_masks, float('-inf'))
        

        
        # decode to bbox
        if has_obj:
            hidden_states = torch.stack(model_output.hidden_states, dim=1)[:, -1:, prompt_length-1:-1].permute(2, 1, 0, 3).unsqueeze(dim=-2).contiguous() # [BS, Layers, N, Dim] -> [N, Layers, BS, 1, D]
            completions, feats, labels, vps, vps_feats = parseVRTintoCompletion(self.processing_class, completion_ids, hidden_states, torch.tensor([False] * batch_size), model_output.past_image_embeds, multimodal_inputs['image_grid_thw']) # hidden_states: [N, Layers, BS, D]
            low_res_image_embeds = model_output.past_image_embeds
            high_res_image_embeds = model_output.past_high_res_image_embeds
            visual_pe = model_output.past_visual_pe
            
            # warm up stage: using visual prototype rather than hidden features to feed into decoder.
            if self.state.epoch < (self.state.num_train_epochs / 4) and self.state.global_step < 300 and self.args.use_warm_up:
                feats = vps_feats
            decoded_list = model(feats, low_res_image_embeds, high_res_image_embeds, multimodal_inputs['image_grid_thw'], visual_pe, is_main=False)
        
        del model_output


        if self.args.use_mask_loss:
            if has_obj:
                gt_mask = torch.zeros_like(decoded_list['pred_mask'])
                loss_mask = torch.zeros_like(decoded_list['pred_mask'])

                obj_idx = 0
                for sol in solutions:
                    for obj in sol['objects']:
                        if 'rle' in obj:
                            gt_m = mask.decode(obj['rle'])
                            mask_h, mask_w = decoded_list['pred_mask_valid_hw'][0][obj_idx].item(), decoded_list['pred_mask_valid_hw'][1][obj_idx].item()
                            resized_gt_m = torch.from_numpy(cv2.resize(gt_m.astype(np.float32()), (mask_w * 4, mask_h * 4)) > 0.5).to(gt_mask.dtype).to(gt_mask.device)
                            gt_mask[obj_idx, :mask_h * 4, :mask_w * 4] = resized_gt_m
                            loss_mask[obj_idx, :mask_h * 4, :mask_w * 4] = 1.0
                        obj_idx += 1
                mask_loss = self.dice_loss(decoded_list['pred_mask'], gt_mask, loss_mask) + self.sigmoid_focal_loss(decoded_list['pred_mask'], gt_mask, loss_mask)
            else:
                mask_loss = torch.tensor(0., device=logits.device, dtype=logits.dtype)
                
            self._metrics['mask_loss'].append(self.accelerator.gather_for_metrics(mask_loss).mean().item())
        else:
            mask_loss = 0.
            


        # token loss
        logit_log_probs = logits.log_softmax(dim=-1)
        token_log_prob = torch.gather(logit_log_probs, dim=-1, index=input_ids.unsqueeze(-1)).squeeze(-1)
        per_token_loss = -token_log_prob
        sft_loss = ((per_token_loss * completion_mask).sum(dim=-1) / (completion_mask.sum(dim=-1) + 1e-4)).to(logits.dtype)
        self._metrics['sft_loss'].append(self.accelerator.gather_for_metrics(sft_loss).mean().item())
        

        
        if self.args.use_bbox_loss:
            if has_obj:
                # bbox loss
                pred_bboxes = decoded_list['pred_boxes']  # num_bbox, 4 [cx, cy, w, h]
                # gt_bboxes # num_bbox, 4 [x1, y1, x2, y2]
                num_bboxes = gt_bboxes.shape[0]
                giou, iou = self.generalized_box_iou(self.box_cxcywh_to_xyxy(pred_bboxes), gt_bboxes)
                giou = torch.diag(giou).to(pred_bboxes.dtype)
                bbox_loss = 1. - giou.sum() / (num_bboxes + 1e-4)
                bbox_loss += torch.nn.functional.l1_loss(pred_bboxes, self.box_xyxy_to_cxcywh(gt_bboxes), reduction='none').sum() / (num_bboxes + 1e-4)
                iou_loss = torch.diag(iou).sum() / (num_bboxes + 1e-4)
                giou_loss = giou.sum() / (num_bboxes + 1e-4)
            else:
                bbox_loss = torch.tensor(0., device=logits.device, dtype=logits.dtype)
                iou_loss = torch.tensor(1., device=logits.device, dtype=logits.dtype)
                giou_loss = torch.tensor(1., device=logits.device, dtype=logits.dtype)
            
            self._metrics['bbox_loss'].append(self.accelerator.gather_for_metrics(bbox_loss).mean().item())
            self._metrics['iou'].append(self.accelerator.gather_for_metrics(iou_loss).mean().item())
            self._metrics['giou'].append(self.accelerator.gather_for_metrics(giou_loss).mean().item())
        else:
            bbox_loss = 0.

            
        if self.args.use_bbox_loss and self.args.use_score_loss:
            if has_obj:
                # score loss
                pred_score = decoded_list['pred_score'].sigmoid() * 2. - 1.  # [-1, 1]
                score_loss = torch.nn.functional.mse_loss(pred_score, giou.unsqueeze(1).detach(), reduction='sum') / (num_bboxes + 1e-4)
            else:
                score_loss = torch.tensor(0., device=logits.device, dtype=logits.dtype)
                
            self._metrics['score_loss'].append(self.accelerator.gather_for_metrics(score_loss).mean().item())
        else:
            score_loss = 0.
            
        loss = sft_loss.mean() + bbox_loss + score_loss + mask_loss
        print(f"{rank}|{has_obj}:Compute loss {loss.item()} done.")
        return loss
```
With this modification, the trainer no longer crashes when processing object-free images.
However, a new problem appears:

---

# ❌ New problem: training gets stuck during backward()

When running distributed training (DS ZeRO-2), the process hangs at backward, and eventually NCCL raises a timeout error.

Typical log:
```
NCCL WARN Timeout waiting for data
NCCL ERROR ncclCommWatchDog: Fatal error
```
This only happens when the batch contains no objects.

It looks like some gradients / tensors may have inconsistent shapes across processes, causing an all-reduce hang.

and it will always happen when a batch contains empty object image like this:
```
0|True:Compute loss 1032.0 done.3|True:Compute loss 1136.0 done.1|True:Compute loss 784.0 done.2|True:Compute loss 628.0 done.
{'loss': 895.0, 'grad_norm': 615.6828002929688, 'learning_rate': 1.988888888888889e-05, 'sft_loss': 2.765625, 'bbox_loss': 892.0, 'iou': 0.0, 'giou': -0.9140625, 'score_loss': 0.01104736328125, 'epoch': 0.02}
1|True:Compute loss 1328.0 done.0|True:Compute loss 1248.0 done.3|True:Compute loss 904.0 done.2|True:Compute loss 508.0 done.
{'loss': 997.0, 'grad_norm': 303.4627990722656, 'learning_rate': 1.987037037037037e-05, 'sft_loss': 3.109375, 'bbox_loss': 996.0, 'iou': 0.0, 'giou': -0.91015625, 'score_loss': 0.0184326171875, 'epoch': 0.03}
0|True:Compute loss 620.0 done.3|True:Compute loss 708.0 done.1|True:Compute loss 976.0 done.2|False:Compute loss 3.546875 done.
```

where log is `{rank}|{is_having_object}:compute_loss status` format

---

# ✔️ System / Training Configuration
```
torch.distributed.run with 4 A6000 GPUs
Deepspeed ZeRO-3 config
bf16 training
```
---
# ❓ My question

Could you help clarify:
	1.	Does the released training code officially support images without objects?
	2.	If not, what is the recommended way to disable box/mask/score losses for empty samples?
	3.	Is there anywhere else in the model that assumes at least one object exists?
	4.	Do you know why distributed backward would hang specifically when has_obj=False?
	•	My suspicion: some losses become scalar 0 but others expect per-object batch sizes, causing mismatch across ranks?

Any suggestions or hints would be greatly appreciated. I’d be happy to test or provide more logs if needed.

**Comment by Dyb3438** [comment]
Might you could refer to this: https://github.com/Gorilla-Lab-SCUT/PaDT/issues/16#issuecomment-3551829146

**Comment by Dyb3438** [comment]
If you are interested, you could also see my fork repo: https://github.com/Dyb3438/PaDT. Here I implement the PaDT to support multi-round conversation and some samples with no objects.

**Comment by eeNickTang** [comment]
I have resolved this issue. Thanks again for your timely reply!@Dyb3438 

# Root Cause
The hanging was caused by inconsistent forward processes across different ranks during distributed training (DDP/DeepSpeed). Specifically, when a batch contained no objects, the decoder execution was skipped in the else branch. This caused the computation graph to be disconnected for those specific parameters, leading to a deadlock during the gradient synchronization phase.

# Solution
I implemented a dummy execution logic. Now, even if a batch contains no objects, the model forces a forward pass through the decoder using dummy inputs (scaled by 0.0 to ensure they don't affect the actual loss value but keep the gradient graph connected). This ensures the computation graph remains consistent across all processes.

# Code Change

Below is my code for those who encounters the same issue 

change in `src/PaDT/trainer/padt_sft_trainer.py`
```python
def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):        
        if return_outputs:
            raise ValueError("The PaDTTrainer does not support returning outputs")

        prompt_text = [self.processing_class.apply_chat_template(i['prompt'], tokenize=False, add_generation_prompt=True) for i in inputs]
        
        images = []
        completions = []
        solutions = []
        for idx, x in enumerate(inputs):
            # input_images
            assert len(x['image_path']) == 1, "current support only an image per sample"

            for img in x['image_path']:
                image = PIL.Image.open(img)
                try:
                    w, h = image.size
                    if w < 28 or h < 28:
                        if w < h:
                            new_w = 28
                            new_h = int(h * (28 / w))
                        else:
                            new_h = 28
                            new_w = int(w * (28 / h))
                    image = image.resize((new_w, new_h), PIL.Image.Resampling.LANCZOS)
                except:
                    pass
                images.append(image)
            
            # completion
            im_w, im_h = image.size
            patch_w, patch_h = round(im_w / 28), round(im_h / 28)

            solution = x['solution']
            completion = solution['text']
            pattern = r'(<\|Obj_(\d+)\|>)'
            obj_in_completion = re.findall(pattern, completion)
            obj_strs = [i[0] for i in obj_in_completion]
            objs = [solution['objects'][int(i[1])] for i in obj_in_completion]
            pattern_without_matching = r'<\|Obj_\d+\|>'
            completion_parts = re.split(pattern_without_matching, completion)
            
            completion_with_vrt = completion_parts[0]
            new_objs = []
            for obj_str, completion_part, obj in zip(obj_strs, completion_parts[1:], objs):
                obj_ = obj.copy()
                selected_patches = np.array(obj_['patches'])
                if self.args.random_select_patch_num < 0:
                    pick_patch = selected_patches.copy()
                elif self.args.random_select_patch is False:
                    selected_patches_x, selected_patches_y = selected_patches % patch_w, selected_patches // patch_w
                    
                    left_patches_m = selected_patches_x == selected_patches_x.min()
                    right_patches_m = selected_patches_x == selected_patches_x.max()
                    top_patches_m = selected_patches_y == selected_patches_y.min()
                    bottom_patches_m = selected_patches_y == selected_patches_y.max()
                    centre_patches_m = (left_patches_m + right_patches_m + top_patches_m + bottom_patches_m) == 0                        
                    
                    left_patches, right_patches, top_patches, bottom_patches, centre_patches = \
                        selected_patches[left_patches_m], \
                        selected_patches[right_patches_m], \
                        selected_patches[top_patches_m], \
                        selected_patches[bottom_patches_m], \
                        selected_patches[centre_patches_m]
                    if centre_patches_m.sum() == 0:
                        centre_patches = selected_patches
                        
                    pick_patch = np.array([np.random.choice(centre_patches), np.random.choice(left_patches), np.random.choice(top_patches), np.random.choice(right_patches), np.random.choice(bottom_patches)])
                else:
                    if selected_patches.shape[0] < self.args.random_select_patch_num:
                        pick_patch = np.random.choice(selected_patches, self.args.random_select_patch_num, replace=True)
                    else:
                        pick_patch = np.random.choice(selected_patches, self.args.random_select_patch_num, replace=False)
            
                obj_['picked'] = pick_patch
                new_objs.append(obj_)
                completion_with_vrt += self.processing_class.pid2vrt(pick_patch) + completion_part

            solutions.append({
                'text': solution['text'],
                'objects': new_objs
            })
            completions.append(completion_with_vrt + self.processing_class.tokenizer.eos_token)

        # tokenizing
        prompt_inputs = self.processing_class(
            text=prompt_text,
            images=images,
            return_tensors='pt',
            padding=True,
            padding_side='left',
            add_special_tokens=False
        )
        prompt_inputs = super()._prepare_inputs(prompt_inputs)
        prompt_ids, prompt_mask = prompt_inputs["input_ids"], prompt_inputs["attention_mask"]
        batch_size = prompt_ids.size(0)
        prompt_length = prompt_ids.size(1)
        multimodal_inputs = {
            'image_grid_thw': prompt_inputs['image_grid_thw'],
            'pixel_values': prompt_inputs['pixel_values']
        }
        
        completion_inputs = self.processing_class(
            text=completions,
            return_tensors='pt',
            padding=True,
            padding_side='right',
            add_special_tokens=False
        )
        completion_inputs = super()._prepare_inputs(completion_inputs)
        completion_ids, completion_mask = completion_inputs["input_ids"], completion_inputs["attention_mask"]

        # prepare for Robust Per-token Cross-Entropy Loss.
        has_objects_mask = []
        loss_masks = []
        gt_bboxes = []
        vision_patch_nums = torch.nn.functional.pad((multimodal_inputs['image_grid_thw'].cumprod(-1)[:, -1] // (self.model.config.vision_config.spatial_merge_size ** 2)).cumsum(-1), (1, 0), 'constant', 0)
        all_vision_patch_nums = vision_patch_nums[-1]
        for sol, vpn in zip(solutions, vision_patch_nums[:-1]):
            batch_has_obj : bool = len(sol['objects']) != 0
            has_objects_mask.append(batch_has_obj)
            for obj in sol['objects']:
                this_object_loss_mask = torch.zeros((obj['picked'].shape[0], all_vision_patch_nums), device=self.accelerator.device, dtype=torch.bool)
                this_object_loss_mask[:, vpn.item() + np.array(obj['patches'])] = True
                this_object_loss_mask[np.arange(obj['picked'].shape[0]), vpn.item() + obj['picked']] = False
                loss_masks.append(this_object_loss_mask)
                # obj['bbox']: x1, y1, x2, y2. Value in [0, 1].
                gt_bboxes.append(obj['bbox'])
                
        assert len(has_objects_mask) == batch_size
        
        if sum(has_objects_mask) > 0:
            loss_masks = torch.cat(loss_masks, dim=0)
            loss_masks = torch.nn.functional.pad(loss_masks, (self.model_embed_token_size, 0), 'constant', False)
            gt_bboxes = torch.Tensor(gt_bboxes).to(self.accelerator.device).to(torch.bfloat16)
            if len(gt_bboxes.shape) == 1:
                gt_bboxes = gt_bboxes.unsqueeze(dim=-1).repeat_interleave(4, dim=-1)

            

        # Concatenate for full sequence
        input_ids = torch.cat([prompt_ids, completion_ids], dim=1)
        attention_mask = torch.cat([prompt_mask, completion_mask], dim=1)

        input_ids = self.processing_class.assign_to_global_vrt_id(input_ids, multimodal_inputs['image_grid_thw'])

        # Get the current policy's log probabilities
        model_output = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True, **multimodal_inputs)

        logits = model_output.logits[:, prompt_length-1:-1, :]  # (B, L, V)
        input_ids = input_ids[:, prompt_length:]  # (B, L-1), exclude the first input ID since we don't have logits for it
        if self.args.use_sft_vp_mask:
            if batch_has_obj:
                visual_patch_mask = input_ids >= self.model_embed_token_size
                logits[visual_patch_mask] = logits[visual_patch_mask].masked_fill(loss_masks, float('-inf'))
            else:
                # when there is no object, we do not apply any vp mask
                pass
        
        # decode to bbox
        hidden_states = torch.stack(model_output.hidden_states, dim=1)[:, -1:, prompt_length-1:-1].permute(2, 1, 0, 3).unsqueeze(dim=-2).contiguous() # [BS, Layers, N, Dim] -> [N, Layers, BS, 1, D]
        completions, feats, _, _, vps_feats = parseVRTintoCompletion(self.processing_class, completion_ids, hidden_states, torch.tensor([False] * batch_size), model_output.past_image_embeds, multimodal_inputs['image_grid_thw']) # hidden_states: [N, Layers, BS, D]
        low_res_image_embeds = model_output.past_image_embeds
        high_res_image_embeds = model_output.past_high_res_image_embeds
        visual_pe = model_output.past_visual_pe
        
        # warm up stage: using visual prototype rather than hidden features to feed into decoder.
        if self.state.epoch < (self.state.num_train_epochs / 4) and self.state.global_step < 300 and self.args.use_warm_up:
            feats = vps_feats
        decoded_list = model(feats, low_res_image_embeds, high_res_image_embeds, multimodal_inputs['image_grid_thw'], visual_pe, is_main=False)
        
        # decoded_list.rm_dummy(has_objects_mask, device=self.accelerator.device)
        
        real_pred_mask = []
        for sample_index, has_object in enumerate(has_objects_mask):
            sample_count = self.sample_idx.count(sample_index)
            if has_object:
                real_pred_mask.extend([True] * sample_count)
            else:
                real_pred_mask.extend([False] * sample_count)
                
        real_pred_mask = torch.tensor(real_pred_mask, device=device, dtype=torch.bool)
            
        if self.pred_boxes is not None:
            self.pred_boxes = self.pred_boxes[real_pred_mask]
        if self.pred_score is not None:
            self.pred_score = self.pred_score[real_pred_mask]
        if self.pred_mask is not None:
            self.pred_mask = self.pred_mask[real_pred_mask]
        if self.pred_mask_valid_hw:
            Hs, Ws = self.pred_mask_valid_hw
            self.pred_mask_valid_hw = (Hs[real_pred_mask], Ws[real_pred_mask])
        if self.sample_idx is not None:
            self.sample_idx = [s for i, s in enumerate(self.sample_idx) if real_pred_mask[i]]
        
        
        del model_output
            
        if self.args.use_mask_loss:
            if sum(has_objects_mask) > 0:
                gt_mask = torch.zeros_like(decoded_list['pred_mask'])
                loss_mask = torch.zeros_like(decoded_list['pred_mask'])

                obj_idx = 0
                for sol in solutions:
                    for obj in sol['objects']:
                        if 'rle' in obj:
                            gt_m = mask.decode(obj['rle'])
                            mask_h, mask_w = decoded_list['pred_mask_valid_hw'][0][obj_idx].item(), decoded_list['pred_mask_valid_hw'][1][obj_idx].item()
                            resized_gt_m = torch.from_numpy(cv2.resize(gt_m.astype(np.float32()), (mask_w * 4, mask_h * 4)) > 0.5).to(gt_mask.dtype).to(gt_mask.device)
                            gt_mask[obj_idx, :mask_h * 4, :mask_w * 4] = resized_gt_m
                            loss_mask[obj_idx, :mask_h * 4, :mask_w * 4] = 1.0
                        obj_idx += 1
                mask_loss = self.dice_loss(decoded_list['pred_mask'], gt_mask, loss_mask) + self.sigmoid_focal_loss(decoded_list['pred_mask'], gt_mask, loss_mask)
            else:
                # dummy mask_loss
                mask_loss = decoded_list['pred_mask'].sum() * 0.0
                
            self._metrics['mask_loss'].append(self.accelerator.gather_for_metrics(mask_loss).mean().item())
        else:
            mask_loss = 0.
            


        # token loss
        logit_log_probs = logits.log_softmax(dim=-1)
        token_log_prob = torch.gather(logit_log_probs, dim=-1, index=input_ids.unsqueeze(-1)).squeeze(-1)
        per_token_loss = -token_log_prob
        sft_loss = ((per_token_loss * completion_mask).sum(dim=-1) / (completion_mask.sum(dim=-1) + 1e-4)).to(logits.dtype)
        self._metrics['sft_loss'].append(self.accelerator.gather_for_metrics(sft_loss).mean().item())
        

        
        if self.args.use_bbox_loss:
            if sum(has_objects_mask) > 0:
                # bbox loss
                pred_bboxes = decoded_list['pred_boxes']  # num_bbox, 4 [cx, cy, w, h]
                # gt_bboxes # num_bbox, 4 [x1, y1, x2, y2]
                num_bboxes = gt_bboxes.shape[0]
                giou, iou = self.generalized_box_iou(self.box_cxcywh_to_xyxy(pred_bboxes), gt_bboxes)
                giou = torch.diag(giou).to(pred_bboxes.dtype)
                bbox_loss = 1. - giou.sum() / (num_bboxes + 1e-4)
                bbox_loss += torch.nn.functional.l1_loss(pred_bboxes, self.box_xyxy_to_cxcywh(gt_bboxes), reduction='none').sum() / (num_bboxes + 1e-4)
                iou_loss = torch.diag(iou).sum() / (num_bboxes + 1e-4)
                giou_loss = giou.sum() / (num_bboxes + 1e-4)
            else:
                # dummy bbox_loss
                bbox_loss = decoded_list['pred_boxes'].sum() * 0.0
                iou_loss = decoded_list['pred_boxes'].sum() * 0.0 + 1.0
                giou_loss = decoded_list['pred_boxes'].sum() * 0.0 + 1.0
            
            self._metrics['bbox_loss'].append(self.accelerator.gather_for_metrics(bbox_loss).mean().item())
            self._metrics['iou'].append(self.accelerator.gather_for_metrics(iou_loss).mean().item())
            self._metrics['giou'].append(self.accelerator.gather_for_metrics(giou_loss).mean().item())
        else:
            bbox_loss = 0.

            
        if self.args.use_bbox_loss and self.args.use_score_loss:
            if sum(has_objects_mask) > 0:
                # score loss
                pred_score = decoded_list['pred_score'].sigmoid() * 2. - 1.  # [-1, 1]
                score_loss = torch.nn.functional.mse_loss(pred_score, giou.unsqueeze(1).detach(), reduction='sum') / (num_bboxes + 1e-4)
            else:
                # dummy score_loss
                score_loss = decoded_list['pred_score'].sum() * 0.0
                
            self._metrics['score_loss'].append(self.accelerator.gather_for_metrics(score_loss).mean().item())
        else:
            score_loss = 0.
            
        loss = sft_loss.mean() + bbox_loss + score_loss + mask_loss

        return loss
```
---
change in `src/PaDT/models/padt_processor.py`
```python
def parseVRTintoCompletion(processor, completion_ids, hidden_states, need_thinking_mask=None, image_prototype=None, image_grid_thw=None):
    # hidden_states: [N, Layers, BS, 1, D]
    # N: Sequence Length (Prompt + Completion)
    dim = hidden_states[0][-1].shape[-1]
    ret_list = []
    ret_completions = []
    ret_labels = []
    ret_vrts = []
    ret_vrts_feats = []

    if image_grid_thw is not None:
        vision_patch_nums = torch.nn.functional.pad((image_grid_thw.cumprod(-1)[:, -1] // 4).cumsum(-1), (1, 0), 'constant', 0)
    
    if need_thinking_mask is None:
        need_thinking_mask = torch.ones(len(completion_ids)).to(torch.bool)

    for batch_idx, completion in enumerate(completion_ids):
        completion_per_vob = processor.batch_decode(completion)
        completion_str = ''.join(completion_per_vob)
        ret_completions.append(completion_str)
        
        sample_ret_list = []
        sample_ret_labels = []
        sample_ret_vrts = []
        sample_ret_vrts_feats = []

        vob_idx = 0
        without_thinking = not need_thinking_mask[batch_idx].item()
        within_answer_tag = False
        within_object_name_tag = False
        object_idx = -1
        current_label = ""

        try:
            while vob_idx < len(completion_per_vob):
                if processor.tokenizer.eos_token in completion_per_vob[vob_idx]:
                    break
                if within_answer_tag is False and '<' in completion_per_vob[vob_idx] and '</' not in completion_per_vob[vob_idx] and 'answer' in completion_per_vob[vob_idx + 1] and '>' in completion_per_vob[vob_idx + 2]:
                    within_answer_tag = True
                    vob_idx += 3
                    continue
                if within_answer_tag is True or without_thinking:
                    if '</' in completion_per_vob[vob_idx] and 'answer' in completion_per_vob[vob_idx + 1]  and '>' in completion_per_vob[vob_idx + 2]:
                        within_answer_tag = False
                        break
                    else:
                        if '"' in completion_per_vob[vob_idx] and within_object_name_tag is False:
                            within_object_name_tag = True
                            current_label = completion_per_vob[vob_idx].split('"')[1]
                            vob_idx += 1
                            continue

                        if '"' in completion_per_vob[vob_idx] and within_object_name_tag is True:
                            within_object_name_tag = False
                            current_label += completion_per_vob[vob_idx].split('"')[0]
                            current_label = current_label.strip()
                            vob_idx += 1
                            continue
                        
                        if '<|VRT_' in completion_per_vob[vob_idx]:
                            within_object_name_tag = False

                            vrt_hidden_states = []
                            vrts_str = ""

                            while '<|VRT_' in completion_per_vob[vob_idx]:
                                # 正常的提取逻辑
                                vrt_hidden_states.append(hidden_states[vob_idx][-1][batch_idx])
                                vrts_str += completion_per_vob[vob_idx]
                                vob_idx += 1
                            
                            sample_ret_list.append(torch.cat(vrt_hidden_states, dim=0))
                            sample_ret_labels.append(current_label)
                            sample_ret_vrts.append(vrts_str)

                            if image_prototype is not None and image_grid_thw is not None:
                                vrts_ids = processor(text=vrts_str, return_tensors='pt')['input_ids'].to(image_grid_thw.device)[0, ...] + vision_patch_nums[batch_idx] - processor.model_embed_token_size
                                vrts_feats = image_prototype[vrts_ids]
                                sample_ret_vrts_feats.append(vrts_feats)
                            continue
                        
                        if within_object_name_tag:
                            current_label += completion_per_vob[vob_idx]
                vob_idx += 1
            
            # ======================================================================
            # [ADD] Dummy Logic: 处理没有检测到对象的情况
            # ======================================================================
            if len(sample_ret_list) == 0:
                # 1. 构造 Dummy Hidden State
                # 取第0个token的最后一层特征，乘以0.0
                # 这样既保留了 Backbone 的梯度连接，又不影响数值（相当于输入是0）
                # hidden_states[token_idx][layer_idx][batch_idx] -> [1, D]
                dummy_feat = hidden_states[0][-1][batch_idx] * 0.0
                sample_ret_list.append(dummy_feat)
                
                # 2. 填充 Dummy Label 防止列表长度不一致报错
                sample_ret_labels.append("dummy")
                sample_ret_vrts.append("<|dummy|>")

                # 3. 构造 Dummy Prototype (如果需要)
                if image_prototype is not None:
                    # 取 image_prototype 的第一个 vector 乘以 0.0
                    # image_prototype: [Total_Patches, D] -> [1, D]
                    if image_prototype.shape[0] > 0:
                        dummy_proto = image_prototype[0:1] * 0.0
                    else:
                        # 极端情况：如果没有 image patches，构造一个全0 tensor
                        dummy_proto = torch.zeros((1, dim), device=image_grid_thw.device, dtype=hidden_states[0][-1].dtype)
                    sample_ret_vrts_feats.append(dummy_proto)
            # ======================================================================

            ret_list.append(sample_ret_list)
            ret_labels.append(sample_ret_labels)
            ret_vrts.append(sample_ret_vrts)
            ret_vrts_feats.append(sample_ret_vrts_feats)

        except Exception as e:
            # 异常处理里的 Dummy 也要跟上
            print(f"Error in parsing VRT: {e}")
            
            # 构造 fallback dummy
            dummy_feat = hidden_states[0][-1][batch_idx] * 0.0
            ret_list.append([dummy_feat])
            
            ret_labels.append(["dummy_error"])
            ret_vrts.append(["<|dummy_error|>"])
            
            if image_prototype is not None:
                if image_prototype.shape[0] > 0:
                    dummy_proto = image_prototype[0:1] * 0.0
                else:
                    dummy_proto = torch.zeros((1, dim), device=image_grid_thw.device, dtype=hidden_states[0][-1].dtype)
                ret_vrts_feats.append([dummy_proto])
            else:
                ret_vrts_feats.append([])

    return ret_completions, ret_list, ret_labels, ret_vrts, ret_vrts_feats
```

**Comment by wbl66** [comment]
@EERuiTang Thanks for your code!
```
if self.args.use_sft_vp_mask:
    if batch_has_obj:
        visual_patch_mask = input_ids >= self.model_embed_token_size
        logits[visual_patch_mask] = logits[visual_patch_mask].masked_fill(loss_masks, float('-inf'))
    else:
        # when there is no object, we do not apply any vp mask
        pass
```
The **batch_has_obj** here represents whether the last sample of the current batch contains an object. The second line should be modified to `if sum(has_objects_mask) > 0:`
May I ask if I understand correctly

**Comment by eeNickTang** [comment]
@wbl66 
yes, you are absolutely right!
This was generated by copilot's association. I didn't find out this mistake at the first time.😂

Besides, I found out another mistake in here
```python
real_pred_mask = []
        for sample_index, has_object in enumerate(has_objects_mask):
            sample_count = self.sample_idx.count(sample_index)
            if has_object:
                real_pred_mask.extend([True] * sample_count)
            else:
                real_pred_mask.extend([False] * sample_count)
                
        real_pred_mask = torch.tensor(real_pred_mask, device=device, dtype=torch.bool)
```

which should be 
```python
real_pred_mask = []
        for sample_index, has_object in enumerate(has_objects_mask):
            sample_count = self.sample_idx.count(sample_index)
            if has_object:
                real_pred_mask.extend([True] * sample_count)
            else:
                real_pred_mask.extend([False] * sample_count)
                
        real_pred_mask = torch.tensor(real_pred_mask, device=self.accelerator.device, dtype=torch.bool)
```

Thanks again! @wbl66

**Comment by wbl66** [comment]
@EERuiTang Thanks for your timely reply!
After reading all the modified code, I found **the tensors mentioned in this part** are not initialized, so initially they are all **None**. Besides, they are not used in the subsequent code. Please forgive me for being a bit confused. May I ask if these contents were used elsewhere, or if they were just forgotten to be deleted😂.
```
real_pred_mask = []
        for sample_index, has_object in enumerate(has_objects_mask):
            sample_count = self.sample_idx.count(sample_index)
            if has_object:
                real_pred_mask.extend([True] * sample_count)
            else:
                real_pred_mask.extend([False] * sample_count)
                
        real_pred_mask = torch.tensor(real_pred_mask, device=device, dtype=torch.bool)
            
        if self.pred_boxes is not None:
            self.pred_boxes = self.pred_boxes[real_pred_mask]
        if self.pred_score is not None:
            self.pred_score = self.pred_score[real_pred_mask]
        if self.pred_mask is not None:
            self.pred_mask = self.pred_mask[real_pred_mask]
        if self.pred_mask_valid_hw:
            Hs, Ws = self.pred_mask_valid_hw
            self.pred_mask_valid_hw = (Hs[real_pred_mask], Ws[real_pred_mask])
        if self.sample_idx is not None:
            self.sample_idx = [s for i, s in enumerate(self.sample_idx) if real_pred_mask[i]]
```
Any reply would be helpful and greatly appreciated！

**Comment by eeNickTang** [comment]
Sorry, I'm wrong again! 🤯
I forgot I have moved this logic to `src/PaDT/models/padt.py`
I defined a `vl_decode` output dataclass like this
```python
@dataclass
class PaDTVisionDecodeOutput():
    pred_boxes: Optional[torch.FloatTensor] = None # [N_obj, 4]
    pred_score: Optional[torch.FloatTensor] = None # [N_obj, 1]
    pred_mask: Optional[torch.BoolTensor] = None # [N_obj, 4*H_max, 4*W_max]
    pred_mask_valid_hw: Optional[Optional[Tuple[torch.IntTensor]]] = None # [2, N_obj]
    sample_idx: Optional[list] = None
    
    def __getitem__(self, key):
        return getattr(self, key)
    
    def rm_dummy(self, has_objects_mask: list[bool], device: Optional[torch.device]=None):
        real_pred_mask = []
        for sample_index, has_object in enumerate(has_objects_mask):
            sample_count = self.sample_idx.count(sample_index)
            if has_object:
                real_pred_mask.extend([True] * sample_count)
            else:
                real_pred_mask.extend([False] * sample_count)
                
        real_pred_mask = torch.tensor(real_pred_mask, device=device, dtype=torch.bool)
            
        if self.pred_boxes is not None:
            self.pred_boxes = self.pred_boxes[real_pred_mask]
        if self.pred_score is not None:
            self.pred_score = self.pred_score[real_pred_mask]
        if self.pred_mask is not None:
            self.pred_mask = self.pred_mask[real_pred_mask]
        if self.pred_mask_valid_hw:
            Hs, Ws = self.pred_mask_valid_hw
            self.pred_mask_valid_hw = (Hs[real_pred_mask], Ws[real_pred_mask])
        if self.sample_idx is not None:
            self.sample_idx = [s for i, s in enumerate(self.sample_idx) if real_pred_mask[i]]
```
after format `vl_decode` outputs in `src/PaDT/models/padt.py` like this
```python
        if true_value:
            return PaDTVisionDecodeOutput(
                pred_boxes=bbox_output,
                pred_score=score_output,
                pred_mask=mask_logits,
                pred_mask_valid_hw=mask_HWs,
                sample_idx=cu_sample_idx,
            )
        # If no objects were detected, return empty tensors
        else:
            return PaDTVisionDecodeOutput(
                pred_boxes=torch.zeros((0, 4)).to(self.device).to(self.dtype),
                pred_score=torch.zeros((0, 1)).to(self.device).to(self.dtype),
                pred_mask=torch.zeros((0, 8, 8)).to(self.device).to(self.dtype),
                pred_mask_valid_hw=(),
                sample_idx=[],
            )
```

you can use this to remove dummy output
```python
# warm up stage: using visual prototype rather than hidden features to feed into decoder.
if self.state.epoch < (self.state.num_train_epochs / 4) and self.state.global_step < 300 and self.args.use_warm_up:
    feats = vps_feats
decoded_list = model(feats, low_res_image_embeds, high_res_image_embeds, multimodal_inputs['image_grid_thw'], visual_pe, is_main=False)
        
# rm dummy entries
decoded_list.rm_dummy(has_objects_mask, device=self.accelerator.device)
```

**Comment by wbl66** [comment]
@EERuiTang I have fully understood now. Thank you sincerely for your great code and response, which have been very helpful to me！Best wishes for you😄！

**Comment by Dyb3438** [comment]
@EERuiTang I would suggest resampling the batch samples to ensure that each batch contains VRTs. Referring to 

https://github.com/Dyb3438/PaDT/blob/main/src/PaDT/trainer/padt_sft_trainer.py#L100-L129

**Comment by Dyb3438** [comment]
The root reason of it is different forward and backpropagation operation in different GPUs, since some GPUs have VRTs that need to decode but some don't. 

One solution is to fake some VRTs for forward and backward passes to ensure operation consistency. Another simpler approach is to resample, ensuring that each batch either has at least one VRT or none at all acroos all GPUs at the same time.

My code [here](https://github.com/Dyb3438/PaDT) has solved this problem, and it is compatible with our released checkpoints and preprocessed datasets. It can run under all pure-text datasets or mixed text-vrt datasets.

**Comment by Dyb3438** [comment]
I shall merge these code as soon as I am not busy😂.

**Comment by eeNickTang** [comment]
@Dyb3438 
Indeed, I identified the same root cause as you.
Previously, I worked around this issue by adding some dummy / rm_dummy logic, but your updated approach — simply creating an empty `loss_masks` — resolves it in a much cleaner and more elegant way!
Great jobs again!

**Comment by Dyb3438** [comment]
@EERuiTang I think this work could be extended to many downstream tasks, such as pose estimation, tracking (need to support multi-image, but I think it's also easy if you fully understand this code), OCR, and others). And even the CoT process using VRTs yet outputing pure-text is also doable, such as MM-VQA. We would very pleased if you are interested in our MLLM paradigm, and we also believe it will a new paradigm of MLLM which allows truly mix-modality reasoning and generation.

If you have any question in the understanding of VRTs, please free to discuss with me.

**Comment by eeNickTang** [comment]
@Dyb3438 
Interesting ideas! I might try applying this paradigm to some multi-page OCR tasks. Using it to further enhance MLLMs visual reasoning also sounds like a very compelling direction!
